#!/usr/bin/env bash

set -euo pipefail

SCRIPT_NAME="$(basename "$0")"
DEFAULT_PROJECT_NAME="exile_updater"
DEFAULT_AUTHOR="yangyuexiong"
DEFAULT_TARGET="."
CURRENT_TIME="$(date '+%Y-%m-%d %H:%M:%S')"

usage() {
  cat <<EOF
Usage:
  $SCRIPT_NAME [options]

Options:
  -n, --name NAME       Project name. Supports letters, numbers, "_" and "-". Default: ${DEFAULT_PROJECT_NAME}
  -a, --author AUTHOR   Author name written into generated files. Default: ${DEFAULT_AUTHOR}
  -t, --target PATH     Target directory. Default: ${DEFAULT_TARGET}
      --force           Overwrite existing files generated by this script
      --dry-run         Print planned actions without writing files
  -h, --help            Show this help message

Examples:
  ./$SCRIPT_NAME
  ./$SCRIPT_NAME --author yangyuexiong
  ./$SCRIPT_NAME --name exile_updater --target /tmp/demo
  ./$SCRIPT_NAME --name exile-updater --target /tmp/demo
  ./$SCRIPT_NAME --dry-run
EOF
}

PROJECT_NAME="$DEFAULT_PROJECT_NAME"
PROJECT_IDENTIFIER="$DEFAULT_PROJECT_NAME"
AUTHOR="$DEFAULT_AUTHOR"
TARGET_DIR="$DEFAULT_TARGET"
FORCE=0
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    -n|--name)
      [[ $# -ge 2 ]] || { echo "Missing value for $1" >&2; exit 1; }
      PROJECT_NAME="$2"
      shift 2
      ;;
    -a|--author)
      [[ $# -ge 2 ]] || { echo "Missing value for $1" >&2; exit 1; }
      AUTHOR="$2"
      shift 2
      ;;
    -t|--target)
      [[ $# -ge 2 ]] || { echo "Missing value for $1" >&2; exit 1; }
      TARGET_DIR="$2"
      shift 2
      ;;
    --force)
      FORCE=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ ! "$PROJECT_NAME" =~ ^[A-Za-z][A-Za-z0-9_-]*$ ]]; then
  echo "Invalid project name: $PROJECT_NAME" >&2
  echo 'Use a valid project name, for example: exile_updater or operational-risk-updater' >&2
  exit 1
fi

if [[ -z "${AUTHOR// }" ]]; then
  echo "Invalid author: $AUTHOR" >&2
  echo 'Use a non-empty author name.' >&2
  exit 1
fi

PROJECT_IDENTIFIER="${PROJECT_NAME//-/_}"

TARGET_DIR="${TARGET_DIR%/}"
if [[ -z "$TARGET_DIR" ]]; then
  TARGET_DIR="."
fi

log() {
  printf '[init] %s\n' "$1"
}

run_mkdir() {
  local dir="$1"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "mkdir -p $dir"
    return
  fi
  mkdir -p "$dir"
  log "created directory: $dir"
}

write_file() {
  local file="$1"
  local content="$2"

  if [[ -f "$file" && "$FORCE" -ne 1 ]]; then
    log "skip existing file: $file"
    return
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    if [[ -f "$file" ]]; then
      log "overwrite file: $file"
    else
      log "create file: $file"
    fi
    return
  fi

  printf '%s' "$content" > "$file"
  if [[ -f "$file" && "$FORCE" -eq 1 ]]; then
    log "wrote file: $file"
  else
    log "created file: $file"
  fi
}

run_mkdir "$TARGET_DIR"

APP_DIR="$TARGET_DIR/app"

DIRS=(
  "$APP_DIR"
  "$APP_DIR/api"
  "$APP_DIR/api/v1"
  "$APP_DIR/api/v1/endpoints"
  "$APP_DIR/core"
  "$APP_DIR/db"
  "$APP_DIR/models"
  "$APP_DIR/schemas"
  "$APP_DIR/services"
  "$APP_DIR/tasks"
  "$APP_DIR/utils"
  "$APP_DIR/static"
  "$TARGET_DIR/scripts"
  "$TARGET_DIR/tests"
)

for dir in "${DIRS[@]}"; do
  run_mkdir "$dir"
done

write_file "$APP_DIR/__init__.py" ""
write_file "$APP_DIR/api/__init__.py" ""
write_file "$APP_DIR/api/v1/__init__.py" ""
write_file "$APP_DIR/api/v1/endpoints/__init__.py" ""
write_file "$APP_DIR/core/__init__.py" ""
write_file "$APP_DIR/db/__init__.py" ""
write_file "$APP_DIR/models/__init__.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : __init__.py

# 新增模型后，请在这里导入，供 Alembic 自动发现
from app.models.admin import Admin
from app.models.aps_task import ApsTask

__all__ = [
    "Admin",
    "ApsTask",
]
EOF
)"
write_file "$APP_DIR/schemas/__init__.py" ""
write_file "$APP_DIR/services/__init__.py" ""
write_file "$APP_DIR/tasks/__init__.py" ""
write_file "$APP_DIR/utils/__init__.py" ""
write_file "$TARGET_DIR/tests/__init__.py" ""

write_file "$APP_DIR/main.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : main.py

from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from app.api.router import api_router
from app.core.config import get_config
from app.core.exception_handlers import register_exception_handlers
from app.core.lifespan import lifespan
from app.core.middleware import MyMiddleware

project_config = get_config()


def create_app():
    debug = project_config.DEBUG
    kw = {
        "debug": debug
    }

    app = FastAPI(
        title=project_config.DOCS_TITLE,
        description=project_config.DOCS_DESCRIPTION,
        summary=project_config.DOCS_SUMMARY,
        version=project_config.DOCS_VERSION,
        openapi_url=project_config.DOCS_OPENAPI_URL,
        lifespan=lifespan,  # 事件注册(应用启动前与关闭后执行的事件处理器)
        **kw
    )

    # 跨域: 如果 allow_credentials=True，则 allow_origins 不能设置为 ["*"]，必须明确指定允许的域名。
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_credentials=False,
        allow_methods=["*"],
        allow_headers=["*"]
    )

    app.add_middleware(
        MyMiddleware,
        log_headers=debug,
        log_body=debug,
        exclude_paths=["/docs", "/openapi.json", "/redoc", "/static*"],
        sensitive_headers=project_config.SENSITIVE_HEADERS,
        mask_sensitive_headers=project_config.MASK_SENSITIVE_HEADERS,
    )

    # 异常处理器注册
    register_exception_handlers(app, debug)

    # 路由注册
    app.include_router(api_router)

    # 静态资源(生产环境通过配置获取路径)
    static_dir = Path(__file__).resolve().parent / "static"
    app.mount("/static", StaticFiles(directory=str(static_dir)), name="static")

    @app.get("/")
    async def root_redirect():
        return {
            "status": "ok",
        }

    return app


app = create_app()
EOF
)"

write_file "$APP_DIR/api/v1/router.py" "$(cat <<EOF
from fastapi import APIRouter

from app.api.v1.endpoints.health import router as health_router

api_router = APIRouter(prefix="/v1")
api_router.include_router(health_router)
EOF
)"

write_file "$APP_DIR/api/router.py" "$(cat <<EOF
from fastapi import APIRouter

from app.api.v1.router import api_router as api_v1_router

api_router = APIRouter(prefix="/api")
api_router.include_router(api_v1_router)
EOF
)"

write_file "$APP_DIR/api/v1/endpoints/health.py" "$(cat <<EOF
from fastapi import APIRouter

router = APIRouter(tags=["health"])


@router.get("/health", summary="Health check")
def health_check() -> dict[str, str]:
    return {"status": "ok"}
EOF
)"

write_file "$APP_DIR/core/config.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : config.py

import os
from functools import lru_cache
from pathlib import Path
from typing import List, Optional

from loguru import logger
from pydantic_settings import BaseSettings, SettingsConfigDict

BASE_DIR = Path(__file__).resolve().parents[2]
DEFAULT_ENV = "development"
ENV_FILE_ENV_VAR = "ENV_FILE"


def normalize_env(env: Optional[str]) -> str:
    value = (env or "").strip().lower()
    mapping = {
        "dev": "development",
        "development": "development",
        "test": "test",
        "testing": "test",
        "prod": "production",
        "production": "production",
        "stage": "staging",
        "staging": "staging",
    }
    return mapping.get(value, value or DEFAULT_ENV)


ENV_FILE_MAP = {
    "development": ".env.development",
    "test": ".env.test",
    "production": ".env.production",
    "staging": ".env.staging",
}


def resolve_env_files(env_name: str) -> List[Path]:
    if env_name not in ENV_FILE_MAP:
        raise ValueError(f"Unsupported ENV: {env_name}")

    paths: List[Path] = []

    explicit = os.getenv(ENV_FILE_ENV_VAR)
    if explicit:
        explicit_path = Path(explicit)
        if not explicit_path.is_absolute():
            explicit_path = BASE_DIR / explicit_path
        if explicit_path.exists():
            paths.append(explicit_path)
        else:
            raise FileNotFoundError(f"{ENV_FILE_ENV_VAR} 指定的文件不存在: {explicit_path}")

    base_env = BASE_DIR / ".env"
    if base_env.exists():
        paths.append(base_env)

    env_specific = BASE_DIR / ENV_FILE_MAP[env_name]
    if env_specific.exists():
        paths.append(env_specific)

    if paths:
        return paths

    raise FileNotFoundError(
        f"未找到配置文件，请创建 {ENV_FILE_MAP.get(env_name)} 或设置 {ENV_FILE_ENV_VAR}"
    )


BASE_SETTINGS_CONFIG = SettingsConfigDict(
    env_file_encoding="utf-8",
    case_sensitive=False,
    extra="ignore",
)


class BaseConfig(BaseSettings):
    model_config = BASE_SETTINGS_CONFIG

    DOCS_TITLE: str = "${PROJECT_NAME}"
    DOCS_DESCRIPTION: str = "description"
    DOCS_SUMMARY: str = "I hope every day is fulfilling, and everything follows best practices."
    DOCS_VERSION: str = "1.0.0"
    DOCS_OPENAPI_URL: str = "/api/v1/openapi.json"

    APP_NAME: str = "${AUTHOR}"
    ENV: str = "development"
    DB_BACKEND: str = "mysql"
    SECRET_KEY: str = "change-me"
    DEBUG: bool = True
    RUN_HOST: str = "0.0.0.0"
    RUN_PORT: int = 8000

    MYSQL_HOSTNAME: str = "127.0.0.1"
    MYSQL_USERNAME: str = "root"
    MYSQL_PASSWORD: str = "password"
    MYSQL_PORT: int = 3306
    MYSQL_DATABASE: str = "${PROJECT_IDENTIFIER}"

    POSTGRESQL_HOSTNAME: str = "127.0.0.1"
    POSTGRESQL_USERNAME: str = "postgres"
    POSTGRESQL_PASSWORD: str = "password"
    POSTGRESQL_PORT: int = 5432
    POSTGRESQL_DATABASE: str = "${PROJECT_IDENTIFIER}"

    REDIS_HOST: str = "127.0.0.1"
    REDIS_PORT: int = 6379
    REDIS_PWD: str = ""
    REDIS_DB: int = 0
    DECODE_RESPONSES: bool = True
    CELERY_BROKER_URL: Optional[str] = None
    CELERY_RESULT_BACKEND: Optional[str] = None
    CELERY_TASK_QUEUE: str = "${PROJECT_IDENTIFIER}_task_queue"

    SENSITIVE_HEADERS: str = "authorization,cookie,set-cookie,x-api-key"

    @property
    def ENV_NAME(self) -> str:
        return normalize_env(self.ENV)

    @property
    def IS_DEV(self) -> bool:
        return self.ENV_NAME == "development"

    @property
    def IS_TEST(self) -> bool:
        return self.ENV_NAME == "test"

    @property
    def IS_PROD(self) -> bool:
        return self.ENV_NAME == "production"

    @property
    def IS_STAGING(self) -> bool:
        return self.ENV_NAME == "staging"

    @property
    def MASK_SENSITIVE_HEADERS(self) -> bool:
        return self.IS_PROD or self.IS_STAGING

    @property
    def redis_url(self) -> str:
        auth = f":{self.REDIS_PWD}@" if self.REDIS_PWD else ""
        return f"redis://{auth}{self.REDIS_HOST}:{self.REDIS_PORT}/{self.REDIS_DB}?decode_responses={self.DECODE_RESPONSES}"

    @property
    def redis_transport_url(self) -> str:
        auth = f":{self.REDIS_PWD}@" if self.REDIS_PWD else ""
        return f"redis://{auth}{self.REDIS_HOST}:{self.REDIS_PORT}/{self.REDIS_DB}"

    @property
    def celery_broker_url(self) -> str:
        return self.CELERY_BROKER_URL or self.redis_transport_url

    @property
    def celery_result_backend(self) -> str:
        return self.CELERY_RESULT_BACKEND or self.redis_transport_url

    @property
    def mysql_url(self) -> str:
        return "mysql://{}:{}@{}:{}/{}".format(
            self.MYSQL_USERNAME,
            self.MYSQL_PASSWORD,
            self.MYSQL_HOSTNAME,
            self.MYSQL_PORT,
            self.MYSQL_DATABASE
        )

    @property
    def mysql_async_url(self) -> str:
        return "mysql+asyncmy://{}:{}@{}:{}/{}".format(
            self.MYSQL_USERNAME,
            self.MYSQL_PASSWORD,
            self.MYSQL_HOSTNAME,
            self.MYSQL_PORT,
            self.MYSQL_DATABASE
        )

    @property
    def pg_url(self) -> str:
        return "postgres://{}:{}@{}:{}/{}".format(
            self.POSTGRESQL_USERNAME,
            self.POSTGRESQL_PASSWORD,
            self.POSTGRESQL_HOSTNAME,
            self.POSTGRESQL_PORT,
            self.POSTGRESQL_DATABASE
        )

    @property
    def pg_async_url(self) -> str:
        return "postgresql+asyncpg://{}:{}@{}:{}/{}".format(
            self.POSTGRESQL_USERNAME,
            self.POSTGRESQL_PASSWORD,
            self.POSTGRESQL_HOSTNAME,
            self.POSTGRESQL_PORT,
            self.POSTGRESQL_DATABASE
        )

    @property
    def sqlalchemy_database_url(self) -> str:
        backend = (self.DB_BACKEND or "mysql").lower()
        if backend == "mysql":
            return self.mysql_async_url
        if backend in {"postgres", "postgresql"}:
            return self.pg_async_url
        raise ValueError(f"Unsupported DB_BACKEND: {self.DB_BACKEND}")


@lru_cache
def get_config(env: Optional[str] = None) -> BaseConfig:
    fast_api_env = normalize_env(env or os.getenv("FAST_API_ENV", DEFAULT_ENV))
    env_files = resolve_env_files(fast_api_env)
    logger.info(f"加载配置: env={fast_api_env}, files={[str(p) for p in env_files]}")
    conf = BaseConfig(_env_file=[str(p) for p in env_files])
    if conf.ENV_NAME != fast_api_env:
        logger.warning(f"ENV 不一致：FAST_API_ENV={fast_api_env}, 配置 ENV={conf.ENV_NAME}")
    return conf


if __name__ == "__main__":
    dev_config = get_config("development")
    print(dev_config.model_dump())
    print(dev_config.APP_NAME)
    print(dev_config.MYSQL_HOSTNAME)

    pro_config = get_config("production")
    print(pro_config.model_dump())
EOF
)"

write_file "$APP_DIR/core/custom_exception.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : custom_exception.py

from typing import Any

from fastapi import HTTPException


class CustomException(HTTPException):
    def __init__(
        self,
        status_code: int = 200,
        detail: str = "出现异常",
        custom_code: int = 200,
        data: Any = None,
    ) -> None:
        super().__init__(status_code=status_code, detail=detail)
        self.custom_code = custom_code
        self.data = data
EOF
)"

write_file "$APP_DIR/core/exception_handlers.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : exception_handlers.py

from typing import Any, Optional

from fastapi import FastAPI, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from loguru import logger

from app.core.custom_exception import CustomException


def register_exception_handlers(app: FastAPI, debug: bool):
    def _get_request_id(request: Request) -> Optional[str]:
        return getattr(request.state, "request_id", None) or request.headers.get("x-request-id")

    def _build_response(
        *,
        code: int,
        message: str,
        http_status: int,
        data: Any = None,
        request_id: Optional[str] = None,
    ) -> JSONResponse:
        content = {
            "code": code,
            "message": message,
            "data": data,
        }
        if data is None:
            content.pop("data")
        if request_id:
            content["request_id"] = request_id
        return JSONResponse(status_code=http_status, content=content)

    @app.exception_handler(CustomException)
    async def custom_exception_handler(request: Request, exc: CustomException):
        request_id = _get_request_id(request)
        logger.bind(request_id=request_id).warning(f"CustomException: {exc.detail}")
        return _build_response(
            code=exc.custom_code,
            message=str(exc.detail),
            http_status=exc.status_code,
            data=exc.data,
            request_id=request_id,
        )

    @app.exception_handler(HTTPException)
    async def http_exception_handler(request: Request, exc: HTTPException):
        request_id = _get_request_id(request)
        logger.bind(request_id=request_id).info(f"HTTPException: {exc.detail}")
        return _build_response(
            code=exc.status_code,
            message=str(exc.detail),
            http_status=exc.status_code,
            request_id=request_id,
        )

    @app.exception_handler(Exception)
    async def base_exception_handler(request: Request, exc: Exception):
        request_id = _get_request_id(request)
        logger.bind(request_id=request_id).exception("Unhandled exception")
        data = [str(exc)] if debug else None
        return _build_response(
            code=500,
            message="Internal server error",
            http_status=500,
            data=data,
            request_id=request_id,
        )

    @app.exception_handler(RequestValidationError)
    async def validation_exception_handler(request: Request, exc: RequestValidationError):
        request_id = _get_request_id(request)
        error_messages = []
        if debug:
            for error in exc.errors():
                error_messages.append({
                    "type": "validation_error",
                    "msg": error.get("msg"),
                    "loc": list(error.get("loc")),
                    "input": error.get("type"),
                })
        return _build_response(
            code=400,
            message="缺少必要的参数，参数类型错误",
            http_status=400,
            data=error_messages if debug else None,
            request_id=request_id,
        )
EOF
)"

write_file "$APP_DIR/core/lifespan.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : lifespan.py

import datetime
import os
import platform
import threading
from contextlib import asynccontextmanager, suppress

from apscheduler.schedulers.base import SchedulerNotRunningError
from fastapi import FastAPI
from loguru import logger

import app.db.redis_client as redis_module
from app.core.config import get_config
from app.db.redis_client import close_redis_connection_pool, create_redis_connection_pool
from app.db.session import close_db, init_db
from app.tasks.scheduler import scheduler, scheduler_init

project_config = get_config()


def _log_startup_info() -> None:
    fast_api_env = os.getenv("FAST_API_ENV", "development")
    logger.info(">>> startup")
    logger.info("<" + "-" * 66 + ">")
    logger.info(f"时间: {datetime.datetime.now()}")
    logger.info(f"操作系统: {platform.system()}")
    logger.info(f"项目路径: {os.getcwd()}")
    logger.info(f"当前环境: {fast_api_env} (config: {project_config.ENV})")
    logger.info(f"父进程id: {os.getppid()}")
    logger.info(f"子进程id: {os.getpid()}")
    logger.info(f"线程id: {threading.get_ident()}")
    logger.info("<" + "-" * 66 + ">")


async def _init_db() -> None:
    logger.info(">>> Mysql连接池初始化")
    await init_db()


async def _init_redis() -> None:
    logger.info(">>> Redis连接池初始化")
    await create_redis_connection_pool()
    logger.debug(f"redis_pool: {redis_module.redis_pool!r}")
    logger.info(">>> Redis 连接池初始化完成")


async def _init_scheduler() -> None:
    await scheduler_init()
    logger.info(">>> 定时任务初始化")


async def _shutdown_scheduler() -> None:
    if getattr(scheduler, "running", False):
        try:
            with suppress(SchedulerNotRunningError):
                scheduler.shutdown(wait=False)
            logger.info(">>> 定时任务已关闭")
        except Exception:
            logger.exception(">>> 定时任务关闭失败")
    else:
        logger.info(">>> 定时任务未启动，跳过关闭")


async def _shutdown_redis() -> None:
    try:
        await close_redis_connection_pool()
        logger.info(">>> Redis 连接池已关闭")
    except Exception:
        logger.exception(">>> Redis 连接池关闭失败")


async def _shutdown_db() -> None:
    try:
        await close_db()
        logger.info(">>> 数据库连接已关闭")
    except Exception:
        logger.exception(">>> 数据库连接关闭失败")


async def startup_event() -> None:
    _log_startup_info()
    logger.info(f">>> Config初始化: {project_config.ENV}")

    try:
        await _init_db()
        await _init_redis()
        # await _init_scheduler()
    except Exception:
        logger.exception("应用启动失败，开始回收资源")
        await _shutdown_scheduler()
        await _shutdown_redis()
        await _shutdown_db()
        raise


async def shutdown_event() -> None:
    logger.info(">>> shutdown")
    # await _shutdown_scheduler()
    await _shutdown_redis()
    await _shutdown_db()


@asynccontextmanager
async def lifespan(app: FastAPI):
    del app
    await startup_event()
    try:
        yield
    finally:
        await shutdown_event()
EOF
)"

write_file "$APP_DIR/core/middleware.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : middleware.py

import json
import time
from typing import Iterable, Optional, Union

import shortuuid
from loguru import logger
from starlette.types import ASGIApp, Receive, Scope, Send


def _decode_headers(raw_headers) -> dict:
    return {k.decode().lower(): v.decode() for k, v in raw_headers}


def _mask_headers(headers: dict, sensitive_headers: set, mask: bool) -> dict:
    if not mask:
        return headers
    return {k: ("***" if k in sensitive_headers else v) for k, v in headers.items()}


def _parse_header_list(value: Union[str, Iterable[str], None]) -> set:
    if not value:
        return set()
    if isinstance(value, str):
        return {h.strip().lower() for h in value.split(",") if h.strip()}
    return {str(h).strip().lower() for h in value if str(h).strip()}


def _get_client_ip(headers: dict, client) -> str:
    xff = headers.get("x-forwarded-for")
    if xff:
        return xff.split(",")[0].strip()
    if client:
        return client[0]
    return "0.0.0.0"


class RequestLoggingMiddleware:
    def __init__(
            self,
            app: ASGIApp,
            *,
            log_headers: bool = False,
            log_body: bool = False,
            max_body_size: int = 1024 * 1024,
            exclude_paths: Optional[Iterable[str]] = None,
            sensitive_headers: Union[str, Iterable[str], None] = None,
            mask_sensitive_headers: bool = True,
    ):
        self.app = app
        self.log_headers = log_headers
        self.log_body = log_body
        self.max_body_size = max_body_size
        self.exclude_paths = set(exclude_paths or [])
        self.sensitive_headers = _parse_header_list(sensitive_headers)
        self.mask_sensitive_headers = mask_sensitive_headers

    def _is_excluded(self, path: str) -> bool:
        for p in self.exclude_paths:
            if p.endswith("*") and path.startswith(p[:-1]):
                return True
            if path == p:
                return True
        return False

    def _should_read_body(self, method: str, headers: dict) -> bool:
        if not self.log_body:
            return False
        if method in {"GET", "HEAD", "OPTIONS"}:
            return False
        content_type = headers.get("content-type", "").lower()
        if content_type.startswith("multipart/form-data"):
            return False
        try:
            content_length = int(headers.get("content-length", "0") or 0)
        except ValueError:
            return False
        if content_length <= 0 or content_length > self.max_body_size:
            return False
        return True

    async def _receive_body(self, receive: Receive) -> tuple[bytes, bool]:
        body = b""
        disconnected = False

        while True:
            message = await receive()
            msg_type = message.get("type")
            if msg_type == "http.request":
                body += message.get("body", b"")
                if not message.get("more_body", False):
                    break
                continue
            if msg_type == "http.disconnect":
                disconnected = True
                break
        return body, disconnected

    def _build_receive(self, body: bytes, original_receive: Receive, disconnected: bool) -> Receive:
        sent = False

        async def receive() -> dict:
            nonlocal sent
            if not sent:
                sent = True
                return {"type": "http.request", "body": body, "more_body": False}
            if disconnected:
                return {"type": "http.disconnect"}
            return await original_receive()

        return receive

    async def __call__(self, scope: Scope, receive: Receive, send: Send):
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        path = scope.get("path", "")
        if self._is_excluded(path):
            await self.app(scope, receive, send)
            return

        start = time.perf_counter()
        headers = _decode_headers(scope.get("headers", []))
        method = scope.get("method", "")
        query_string = scope.get("query_string", b"").decode()
        client = scope.get("client")
        request_id = headers.get("x-request-id") or headers.get("x-log-uuid") or shortuuid.uuid()
        scope.setdefault("state", {})["request_id"] = request_id

        body = b""
        if self._should_read_body(method, headers):
            body, disconnected = await self._receive_body(receive)
            receive = self._build_receive(body, receive, disconnected)

        status_code = None
        response_headers = []

        async def send_wrapper(message):
            nonlocal status_code, response_headers
            if message["type"] == "http.response.start":
                status_code = message.get("status")
                response_headers = list(message.get("headers", []))
                process_time = time.perf_counter() - start
                response_headers.append((b"x-process-time", f"{process_time:.6f}".encode()))
                if not any(k.lower() == b"x-request-id" for k, _ in response_headers):
                    response_headers.append((b"x-request-id", request_id.encode()))
                message["headers"] = response_headers
            await send(message)

        try:
            await self.app(scope, receive, send_wrapper)
        except Exception:
            logger.exception("请求处理异常")
            raise
        finally:
            elapsed_ms = (time.perf_counter() - start) * 1000
            full_path = f"{path}?{query_string}" if query_string else path
            ip = _get_client_ip(headers, client)
            logger.info(
                f"{method} {full_path} {status_code} {elapsed_ms:.2f}ms "
                f"ip={ip} rid={request_id}"
            )
            if self.log_headers:
                logger.info(
                    f"headers: {_mask_headers(headers, self.sensitive_headers, self.mask_sensitive_headers)}"
                )
            if self.log_body and body:
                content_type = headers.get("content-type", "").lower()
                body_text = body.decode("utf-8", errors="replace")
                if "application/json" in content_type:
                    try:
                        body_data = json.loads(body_text)
                    except Exception:
                        body_data = body_text
                else:
                    body_data = body_text
                logger.info(f"body: {body_data}")


MyMiddleware = RequestLoggingMiddleware
EOF
)"

write_file "$APP_DIR/core/pagination.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : pagination.py

from typing import Dict, List

from pydantic import BaseModel
from sqlalchemy import and_, asc, desc, func, or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.schemas.pagination import page_size, query_result
from app.utils.time_tools import TimeTools


class JsonFieldHandle:
    def __init__(self):
        pass


class CommonPaginateQuery:
    def __init__(
        self,
        request_data: BaseModel,
        orm_model,
        db_session: AsyncSession,
        model_pydantic: BaseModel = None,
        like_list: list = None,
        where_list: list = None,
        order_by_list: list = None,
        filter_range: dict = None,
        json_field_keys_to_obj: List[Dict] = None,
        json_field_obj_to_keys: List[Dict] = None,
        output_model: BaseModel = None,
        exclude_field: set = None,
        skip_list: List = None,
    ):
        self.request_data = request_data
        self.orm_model = orm_model
        self.db_session = db_session
        self.model_pydantic = model_pydantic
        self.like_list = like_list
        self.where_list = where_list
        self.order_by_list = order_by_list
        self.json_field_keys_to_obj = json_field_keys_to_obj
        self.json_field_obj_to_keys = json_field_obj_to_keys
        self.filter_range = filter_range
        self.output_model = output_model
        self.exclude_field = exclude_field or set()

        self.like_conditions = []
        self.where_conditions = []
        self.range_conditions = []
        self.records = []
        self.normal_data = []

        if skip_list:
            self.skip_list = skip_list + ["is_deleted"]
        else:
            self.skip_list = ["is_deleted"]

    @staticmethod
    def _parse_filter_key(key: str) -> tuple[str, str]:
        if "__" in key:
            field, op = key.split("__", 1)
            return field, op
        return key, "eq"

    def _build_expr(self, key: str, value):
        field, op = self._parse_filter_key(key)
        column = getattr(self.orm_model, field, None)
        if column is None:
            return None

        if op == "eq":
            return column == value
        if op == "icontains":
            return column.ilike(f"%{value}%")
        if op == "gte":
            return column >= value
        if op == "lte":
            return column <= value
        if op == "gt":
            return column > value
        if op == "lt":
            return column < value
        if op == "in":
            if not isinstance(value, (list, tuple, set)):
                value = [value]
            return column.in_(value)
        if op == "isnull":
            return column.is_(None) if bool(value) else column.is_not(None)
        return None

    async def build_filter_conditions(self):
        for k, v in self.request_data.model_dump().items():
            if v is None or (bool(v) is False and k not in self.skip_list):
                continue
            if k in self.like_list:
                self.like_conditions.append(getattr(self.orm_model, k).ilike(f"%{v}%"))
            if k in self.where_list:
                self.where_conditions.append(getattr(self.orm_model, k) == v)

    async def build_like(self):
        if not self.like_list:
            self.like_list = []

    async def build_where(self):
        if not self.where_list:
            self.where_list = []

    async def build_range(self):
        if not self.filter_range:
            return
        for k, v in self.filter_range.items():
            if v == "":
                continue
            expr = self._build_expr(k, v)
            if expr is not None:
                self.range_conditions.append(expr)

    async def build_order_by(self):
        if not self.order_by_list:
            self.order_by_list = []

    def _build_order_clauses(self):
        clauses = []
        for field in self.order_by_list:
            if field.startswith("-"):
                key = field[1:]
                column = getattr(self.orm_model, key, None)
                if column is not None:
                    clauses.append(desc(column))
            else:
                column = getattr(self.orm_model, field, None)
                if column is not None:
                    clauses.append(asc(column))
        return clauses

    async def _handle_json_field_keys_to_obj(self, model_data: dict):
        if not self.json_field_keys_to_obj:
            return
        for d in self.json_field_keys_to_obj:
            d_field = d.get("field")
            d_model = d.get("model")
            d_query_key = d.get("query_key")
            d_exclude_field = d.get("exclude_field") or set()
            value = model_data.get(d_field)
            if not (d_field and d_model and d_query_key and isinstance(value, list) and value):
                continue

            query_col = getattr(d_model, d_query_key, None)
            if query_col is None:
                continue
            stmt = select(d_model).where(query_col.in_(value))
            result = await self.db_session.execute(stmt)
            d_model_list = result.scalars().all()
            if not d_model_list:
                continue
            model_data[d_field] = [m.to_dict(exclude=d_exclude_field) for m in d_model_list]

    async def build_query(self):
        await self.build_like()
        await self.build_where()
        await self.build_filter_conditions()
        await self.build_range()
        await self.build_order_by()

        page = self.request_data.page
        now_page = page
        size = self.request_data.size
        offset, limit = page_size(page, size)

        where_clauses = []
        if self.where_conditions:
            where_clauses.extend(self.where_conditions)
        if self.like_conditions:
            where_clauses.append(or_(*self.like_conditions))
        if self.range_conditions:
            where_clauses.extend(self.range_conditions)

        count_stmt = select(func.count()).select_from(self.orm_model)
        if where_clauses:
            count_stmt = count_stmt.where(and_(*where_clauses))
        total_count = (await self.db_session.execute(count_stmt)).scalar_one()

        stmt = select(self.orm_model)
        if where_clauses:
            stmt = stmt.where(and_(*where_clauses))
        order_clauses = self._build_order_clauses()
        if order_clauses:
            stmt = stmt.order_by(*order_clauses)
        stmt = stmt.offset(offset).limit(limit)

        model_list = (await self.db_session.execute(stmt)).scalars().all()

        records = []
        for model in model_list:
            model_data = model.to_dict(exclude=self.exclude_field)
            if model_data.get("create_time"):
                model_data["create_time"] = TimeTools.convert_to_standard_format(model_data["create_time"])
            if model_data.get("update_time"):
                model_data["update_time"] = TimeTools.convert_to_standard_format(model_data["update_time"])
            if model_data.get("go_live_time"):
                model_data["go_live_time"] = TimeTools.convert_to_standard_format(model_data["go_live_time"])

            await self._handle_json_field_keys_to_obj(model_data)
            records.append(model_data)

        if self.output_model:
            records = [self.output_model.model_validate(model).model_dump() for model in records]

        self.records = records
        self.normal_data = query_result(records=self.records, now_page=now_page, total=total_count)
        return self.normal_data
EOF
)"

write_file "$APP_DIR/core/response.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : response.py

from typing import Any

from fastapi.responses import JSONResponse

from app.utils.time_tools import TimeTools


def custom_http_dict(custom_code):
    code_dict = {
        200: "操作成功",
        201: "创建成功",
        203: "编辑成功",
        204: "删除成功",
        401: "未授权",
        500: "服务器异常",
        10001: "必传参数",
        10002: "未找到数据",
        10003: "唯一校验",
        10004: "参数类型错误",
        10005: "业务校验错误",
        10006: "请求参数错误",
        10007: "未公开使用，非创建人，无法修改。",
    }

    message = code_dict.get(custom_code)
    if message:
        return message

    return None


def api_response(
    http_code: int = 200,
    code: int = 200,
    message: str = None,
    data: Any = None,
    datetime_format: bool = True,
    is_pop: bool = True,
) -> JSONResponse:
    if not message:
        message = custom_http_dict(code)

    if data and isinstance(data, dict) and datetime_format:
        if data.get("create_time"):
            data["create_time"] = TimeTools.convert_to_standard_format(data["create_time"])

        if data.get("update_time"):
            data["update_time"] = TimeTools.convert_to_standard_format(data["update_time"])

    content = {
        "code": code,
        "message": message,
        "data": data,
    }

    if not content.get("data") and is_pop:
        content.pop("data")

    return JSONResponse(status_code=http_code, content=content)
EOF
)"

write_file "$APP_DIR/core/password.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : password.py

import bcrypt


def hash_password(password: str) -> str:
    salt = bcrypt.gensalt()
    hashed = bcrypt.hashpw(password.encode(), salt)
    return hashed.decode()


def verify_password(password: str, hashed: str) -> bool:
    return bcrypt.checkpw(password.encode(), hashed.encode())


if __name__ == "__main__":
    raw_password = "password123"
    hashed_password = hash_password(raw_password)
    print(f"Hashed Password: {hashed_password}")

    is_valid = verify_password(raw_password, hashed_password)
    print(f"Password is valid: {is_valid}")

    is_valid = verify_password("wrongpassword", hashed_password)
    print(f"Password is valid: {is_valid}")
EOF
)"

write_file "$APP_DIR/core/enums.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : enums.py

from enum import Enum


class UserStatus(str, Enum):
    normal = "正常"
    disable = "禁用"
EOF
)"

write_file "$APP_DIR/core/security.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : security.py

import json
import secrets

from fastapi import Depends, Header
from loguru import logger
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

import app.db.redis_client as rp
from app.core.custom_exception import CustomException
from app.db.redis_client import get_value, set_key_value
from app.db.session import get_db_session
from app.models.admin import Admin


class Token:
    def __init__(self):
        self.token = None
        self.timeout = 3600 * 24 * 30

    async def gen_token(self):
        token = secrets.token_urlsafe(32)
        self.token = token
        return token

    @staticmethod
    async def get_user_info(token: str):
        query_user_info = await get_value(token)
        if not query_user_info:
            return False
        user_info = json.loads(query_user_info)
        return user_info

    async def single_login(self, key: str, user_info_json_str: str):
        old_key_list = await rp.redis_pool.keys(pattern=f"{key}*")
        old_token_list = [await get_value(old_key) for old_key in old_key_list]
        if old_key_list or old_token_list:
            logger.debug(f"single_login revoke tokens: keys={len(old_key_list)} tokens={len(old_token_list)}")
        if old_key_list:
            await rp.redis_pool.delete(*old_key_list)
        valid_old_tokens = [token for token in old_token_list if token]
        if valid_old_tokens:
            await rp.redis_pool.delete(*valid_old_tokens)

        await self.gen_token()
        await set_key_value(f"{key}{self.token}", self.token, self.timeout)
        await set_key_value(self.token, user_info_json_str, self.timeout)

    async def many_login(self, key: str, user_info_json_str: str):
        await self.gen_token()
        await set_key_value(f"{key}{self.token}", self.token, self.timeout)
        await set_key_value(self.token, user_info_json_str, self.timeout)


async def get_token_header(token: str = Header()):
    query_user_info = await get_value(token)
    if not query_user_info:
        raise CustomException(detail="未授权", custom_code=401)
    user_info = json.loads(query_user_info)
    return user_info


async def check_admin_existence(
    user_info: dict = Depends(get_token_header),
    db: AsyncSession = Depends(get_db_session),
):
    try:
        admin_id = int(user_info.get("id"))
    except (TypeError, ValueError):
        raise CustomException(detail="无效的用户身份", custom_code=401)
    stmt = select(Admin).where(Admin.id == admin_id)
    admin = (await db.execute(stmt)).scalars().first()
    if not admin:
        raise CustomException(detail=f"后台用户 {admin_id} 不存在", custom_code=10002)
    return admin
EOF
)"

write_file "$APP_DIR/db/session.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : session.py

from collections.abc import AsyncGenerator

from loguru import logger
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.core.config import get_config

project_config = get_config()

engine = create_async_engine(
    project_config.sqlalchemy_database_url,
    pool_pre_ping=True,
    pool_recycle=3600,
    echo=project_config.DEBUG,
)

AsyncSessionLocal = async_sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)


async def get_db_session() -> AsyncGenerator[AsyncSession, None]:
    async with AsyncSessionLocal() as session:
        yield session


async def init_db():
    async with engine.begin() as conn:
        await conn.execute(text("SELECT 1"))
    logger.info(">>> 数据库连接池初始化完成")


async def close_db():
    await engine.dispose()
    logger.info(">>> 数据库连接池已关闭")
EOF
)"

write_file "$APP_DIR/db/redis_client.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : redis_client.py

from typing import Optional

from loguru import logger
from redis.asyncio import Redis

from app.core.config import get_config

project_config = get_config()
REDIS_URL = project_config.redis_url

redis_pool: Optional[Redis] = None


async def create_redis_connection_pool(force: bool = False) -> Redis:
    global redis_pool
    if redis_pool and not force:
        return redis_pool
    if redis_pool and force:
        await close_redis_connection_pool()
    redis_pool = Redis.from_url(REDIS_URL)
    logger.info("Redis 连接池已创建")
    return redis_pool


async def close_redis_connection_pool():
    global redis_pool
    if redis_pool:
        close_method = getattr(redis_pool, "aclose", None)
        if close_method:
            await close_method()
        else:
            await redis_pool.close()
        redis_pool = None
        logger.info("Redis 连接池已关闭")


async def get_redis_pool() -> Redis:
    if not redis_pool:
        raise RuntimeError("Redis 连接池未初始化，请先调用 create_redis_connection_pool()")
    return redis_pool


async def set_key_value(key, value, ex=None):
    pool = await get_redis_pool()
    await pool.set(key, value, ex)


async def get_value(key):
    pool = await get_redis_pool()
    value = await pool.get(key)
    return value


async def delete_value(key):
    pool = await get_redis_pool()
    await pool.delete(key)


async def redis_one_get(k):
    redis = Redis.from_url(REDIS_URL)
    res = await redis.get(k)
    await redis.close()
    return res


async def redis_one_set(k, v):
    redis = Redis.from_url(REDIS_URL)
    await redis.set(k, v)
    await redis.close()
EOF
)"

write_file "$APP_DIR/tasks/scheduler.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : scheduler.py

import pytz
from datetime import datetime
from enum import Enum

from apscheduler.jobstores.base import ConflictingIdError
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.cron import CronTrigger
from apscheduler.triggers.date import DateTrigger
from apscheduler.triggers.interval import IntervalTrigger
from sqlalchemy import select

from app.db.session import AsyncSessionLocal
from app.models.aps_task import ApsTask
from app.tasks import tasks as TaskDict

scheduler = AsyncIOScheduler()


class TriggerType(str, Enum):
    date = "date"
    interval = "interval"
    cron = "cron"


class TriggerHandler:
    def __init__(
        self,
        task_id: str,
        trigger_type: TriggerType,
        trigger_time: str = None,
        interval_kw: dict = None,
        cron_expression: str = None,
        timezone=pytz.timezone("Asia/Shanghai"),
        task_function_name: str = None,
        skip_function_check: bool = False,
        task_function=None,
        task_function_args: list = None,
        task_function_kwargs: dict = None,
    ):
        self.task_id = task_id
        self.trigger_type = trigger_type
        self.trigger = None
        self.trigger_param = {}
        self.trigger_time = trigger_time
        self.interval_kw = interval_kw
        self.cron_expression = cron_expression
        self.timezone = timezone
        self.task_function_name = task_function_name
        self.skip_function_check = skip_function_check
        self.task_function = task_function
        self.task_function_args = task_function_args
        self.task_function_kwargs = task_function_kwargs

    def date_trigger(self):
        if not self.trigger_time:
            raise TypeError("DateTrigger 缺少 trigger_time")

        run_date = datetime.strptime(self.trigger_time, "%Y-%m-%d %H:%M:%S")
        trigger = DateTrigger(run_date=run_date, timezone=self.timezone)
        self.trigger_param = {
            "trigger_time": run_date
        }
        return trigger

    def interval_trigger(self):
        if not isinstance(self.interval_kw, dict):
            raise TypeError("IntervalTrigger 参数 interval_kw 错误")

        trigger = IntervalTrigger(timezone=self.timezone, **self.interval_kw)
        self.trigger_param = {
            "interval_kw": self.interval_kw
        }
        return trigger

    def cron_trigger(self):
        if not self.cron_expression:
            raise TypeError("CronTrigger 缺少 cron_expression")

        trigger = CronTrigger.from_crontab(expr=self.cron_expression, timezone=self.timezone)
        self.trigger_param = {
            "cron_expression": self.cron_expression
        }
        return trigger

    def get_trigger(self):
        trigger_dict = {
            "date": self.date_trigger,
            "interval": self.interval_trigger,
            "cron": self.cron_trigger
        }
        self.trigger = trigger_dict.get(self.trigger_type)()
        return self.trigger

    def get_task_function(self):
        if self.skip_function_check:
            return self.task_function

        if hasattr(TaskDict, self.task_function_name):
            self.task_function = getattr(TaskDict, self.task_function_name)
            return self.task_function
        raise AttributeError(f"任务函数 '{self.task_function_name}' 不存在")


class TaskHandler(TriggerHandler):
    def add_task(self):
        self.get_trigger()
        self.get_task_function()

        try:
            scheduler.add_job(
                self.task_function,
                trigger=self.trigger,
                id=self.task_id,
                args=self.task_function_args,
                kwargs=self.task_function_kwargs
            )
            return True, f"定时任务: {self.task_id} 新增成功"
        except ConflictingIdError as e:
            return False, f"定时任务: {self.task_id} 已存在: {e}"

    def update_task(self):
        remove_result, remove_message = self.remove_task(task_id=self.task_id)
        add_result, add_message = self.add_task()
        del remove_message, add_message

        if not remove_result or not add_result:
            return False, f"定时任务: {self.task_id} 更新失败"
        return True, f"定时任务: {self.task_id} 更新成功"

    @classmethod
    def remove_task(cls, task_id):
        if scheduler.get_job(task_id):
            scheduler.remove_job(task_id)
            return True, f"定时任务: {task_id} 删除成功"
        return False, f"定时任务: {task_id} 不存在"

    @classmethod
    def get_task_state(cls, task_id):
        job = scheduler.get_job(task_id)
        if job:
            res = {
                "id": job.id,
                "next_run_time": job.next_run_time
            }
            return res
        return {}

    @staticmethod
    def get_all_task_states():
        all_jobs = scheduler.get_jobs()
        task_states = []
        for job in all_jobs:
            d = {
                "id": job.id,
                "next_run_time": job.next_run_time
            }
            task_states.append(d)
        return task_states


async def scheduler_init():
    async with AsyncSessionLocal() as db:
        stmt = select(ApsTask).where(ApsTask.is_deleted == 0)
        tasks = (await db.execute(stmt)).scalars().all()

    for task in tasks:
        task_id = task.task_id
        trigger_type = task.trigger_type
        trigger_param: dict = task.trigger_param
        task_function_name = task.task_function_name
        task_function_args = task.task_function_args
        task_function_kwargs = task.task_function_kwargs

        if trigger_param:
            task_handler = TaskHandler(
                task_id=task_id,
                trigger_type=trigger_type,
                task_function_name=task_function_name,
                task_function_args=task_function_args,
                task_function_kwargs=task_function_kwargs
            )

            for k, v in trigger_param.items():
                setattr(task_handler, k, v)

            task_handler.add_task()

    test1 = TaskHandler(
        task_id=TaskDict.test_sync_task.__name__,
        trigger_type=TriggerType.interval,
        interval_kw={
            "weeks": 0,
            "days": 0,
            "hours": 0,
            "minutes": 0,
            "seconds": 5,
            "start_date": None,
            "end_date": None
        },
        task_function_name=TaskDict.test_sync_task.__name__
    )
    test1.add_task()

    test2 = TaskHandler(
        task_id=TaskDict.test_async_task.__name__,
        trigger_type=TriggerType.interval,
        interval_kw={
            "weeks": 0,
            "days": 0,
            "hours": 0,
            "minutes": 0,
            "seconds": 5,
            "start_date": None,
            "end_date": None
        },
        task_function_name=TaskDict.test_async_task.__name__
    )
    test2.add_task()

    scheduler.start()
EOF
)"

write_file "$APP_DIR/tasks/celery_app.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : celery_app.py

from celery import Celery

from app.core.config import get_config

project_config = get_config()

celery_app = Celery(
    "${PROJECT_NAME}-service",
    broker=project_config.celery_broker_url,
    backend=project_config.celery_result_backend,
    include=[],
)

celery_app.conf.update(
    task_default_queue=project_config.CELERY_TASK_QUEUE,
    task_track_started=True,
    task_acks_late=True,
    worker_prefetch_multiplier=1,
    broker_connection_retry_on_startup=True,
    task_serializer="json",
    result_serializer="json",
    accept_content=["json"],
    timezone="Asia/Shanghai",
    enable_utc=False,
)
EOF
)"

write_file "$APP_DIR/tasks/tasks.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : tasks.py

from app.core.config import get_config


async def test_async_task(*args, **kwargs):
    import os
    os.environ["yyx"] = "okc"
    print(f"test_async_task: {os.getenv('yyx')}", args, kwargs)


def test_sync_task(*args, **kwargs):
    import os
    print(f"test_sync_task: {os.getenv('yyx')}", args, kwargs)
EOF
)"

write_file "$APP_DIR/models/admin.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : admin.py

from sqlalchemy import BigInteger, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from app.core.password import hash_password, verify_password
from app.models.base import CustomBaseModel


class Admin(CustomBaseModel):
    __table_name__ = "admin"

    username: Mapped[str | None] = mapped_column(String(255), nullable=True, comment="用户名")
    password: Mapped[str] = mapped_column(String(255), nullable=False, comment="密码")
    nickname: Mapped[str | None] = mapped_column(String(128), nullable=True, comment="昵称")
    phone: Mapped[str | None] = mapped_column(String(64), nullable=True, comment="手机号")
    mail: Mapped[str | None] = mapped_column(String(256), nullable=True, comment="邮箱")
    code: Mapped[str | None] = mapped_column(String(64), nullable=True, comment="用户编号")
    seat: Mapped[str | None] = mapped_column(String(64), nullable=True, comment="座位编号")
    department: Mapped[str | None] = mapped_column(String(64), nullable=True, comment="部门")
    position: Mapped[str | None] = mapped_column(String(64), nullable=True, comment="职位")
    superior: Mapped[str | None] = mapped_column(String(64), nullable=True, comment="上级")
    login_type: Mapped[str | None] = mapped_column(String(64), nullable=True, default="single", comment="登录类型:single;many")
    is_tourist: Mapped[int] = mapped_column(Integer, default=1, nullable=False, comment="0-游客账户;1-非游客账户")
    creator: Mapped[str | None] = mapped_column(String(32), nullable=True, comment="创建人")
    creator_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True, comment="创建人id")
    modifier: Mapped[str | None] = mapped_column(String(32), nullable=True, comment="更新人")
    modifier_id: Mapped[int | None] = mapped_column(BigInteger, nullable=True, comment="更新人id")
    remark: Mapped[str | None] = mapped_column(String(255), nullable=True, comment="备注")

    async def set_password(self, raw_password: str):
        self.password = hash_password(raw_password)

    async def verify_password(self, raw_password: str):
        return verify_password(raw_password, self.password)
EOF
)"

write_file "$APP_DIR/models/base.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : base.py

import json
import re
import time
from datetime import date, datetime
from decimal import Decimal
from typing import Any, Optional

import pytz
from sqlalchemy import BigInteger, DateTime, Integer, event
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column


class Base(DeclarativeBase):
    pass


TZ = pytz.timezone("Asia/Shanghai")


def camel_to_snake(name: str) -> str:
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def shanghai_now(*, naive: bool = False) -> datetime:
    dt = datetime.now(TZ)
    if naive:
        return dt.replace(tzinfo=None)
    return dt


def shanghai_datetime(value: Optional[datetime], *, naive: bool = False) -> Optional[datetime]:
    if value is None:
        return None
    if value.tzinfo is None:
        localized_value = TZ.localize(value)
    else:
        localized_value = value.astimezone(TZ)
    if naive:
        return localized_value.replace(tzinfo=None)
    return localized_value


class CustomBaseModel(Base):
    __abstract__ = True
    _json_string_fields: set[str] = set()
    __table_prefix__ = ""  # 表名称前缀
    __table_name__: str | None = None
    __enable_auto_id__ = True
    __enable_audit_columns__ = True

    @declared_attr.directive
    def __tablename__(cls) -> str:
        suffix = cls.__dict__.get("__table_name__") or camel_to_snake(cls.__name__)
        prefix = getattr(cls, "__table_prefix__", "")  # 表名称前缀
        if suffix.startswith(prefix):
            return suffix
        return f"{prefix}{suffix}"

    @declared_attr
    def id(cls) -> Mapped[int]:
        if not getattr(cls, "__enable_auto_id__", True):
            return None
        return mapped_column(Integer, primary_key=True, autoincrement=True, comment="ID", sort_order=-1000)

    @declared_attr
    def create_time(cls) -> Mapped[datetime]:
        if not getattr(cls, "__enable_audit_columns__", True):
            return None
        return mapped_column(
            DateTime(timezone=True),
            nullable=False,
            default=lambda: shanghai_now(naive=True),
            comment="创建时间",
            sort_order=1000,
        )

    @declared_attr
    def update_time(cls) -> Mapped[datetime]:
        if not getattr(cls, "__enable_audit_columns__", True):
            return None
        return mapped_column(
            DateTime(timezone=True),
            nullable=False,
            default=lambda: shanghai_now(naive=True),
            onupdate=lambda: shanghai_now(naive=True),
            comment="更新时间",
            sort_order=1001,
        )

    @declared_attr
    def create_timestamp(cls) -> Mapped[int]:
        if not getattr(cls, "__enable_audit_columns__", True):
            return None
        return mapped_column(BigInteger, nullable=False, default=lambda: int(time.time()), comment="创建时间戳", sort_order=1002)

    @declared_attr
    def update_timestamp(cls) -> Mapped[int]:
        if not getattr(cls, "__enable_audit_columns__", True):
            return None
        return mapped_column(
            BigInteger,
            nullable=False,
            default=lambda: int(time.time()),
            onupdate=lambda: int(time.time()),
            comment="更新时间戳",
            sort_order=1003,
        )

    @declared_attr
    def is_deleted(cls) -> Mapped[int]:
        if not getattr(cls, "__enable_audit_columns__", True):
            return None
        return mapped_column(BigInteger, nullable=True, default=0, comment="逻辑删除标识", sort_order=1004)

    @declared_attr
    def status(cls) -> Mapped[int]:
        if not getattr(cls, "__enable_audit_columns__", True):
            return None
        return mapped_column(BigInteger, nullable=True, default=1, comment="状态(通用字段)", sort_order=1005)

    def touch(self):
        mapper_columns = self.__mapper__.columns
        now = shanghai_now(naive=True)
        if "update_time" in mapper_columns:
            setattr(self, "update_time", now)
        if "update_timestamp" in mapper_columns:
            setattr(self, "update_timestamp", int(time.time()))

    def _serialize_value(self, key: str, value: Any) -> Any:
        if isinstance(value, date) and not isinstance(value, datetime):
            return value.isoformat()
        if isinstance(value, datetime):
            localized_value = shanghai_datetime(value)
            if localized_value is not None:
                return localized_value.strftime("%Y-%m-%d %H:%M:%S")
            return value
        if isinstance(value, Decimal):
            return float(value)
        if key in self._json_string_fields and isinstance(value, str):
            v = value.strip()
            if (v.startswith("{") and v.endswith("}")) or (v.startswith("[") and v.endswith("]")):
                try:
                    return json.loads(v)
                except json.JSONDecodeError:
                    return value
        return value

    def to_dict(self, exclude: Optional[set[str]] = None, include: Optional[set[str]] = None) -> dict[str, Any]:
        exclude = exclude or set()
        data = {}
        for column in self.__mapper__.columns:
            key = column.key
            if include is not None and key not in include:
                continue
            if key in exclude:
                continue
            data[key] = self._serialize_value(key, getattr(self, key, None))
        return data


@event.listens_for(CustomBaseModel, "before_insert", propagate=True)
def _before_insert_set_audit_timezone(_mapper, _connection, target: CustomBaseModel) -> None:
    mapper_columns = target.__mapper__.columns
    now = shanghai_now(naive=True)
    now_ts = int(time.time())
    if "create_time" in mapper_columns:
        create_time = shanghai_datetime(getattr(target, "create_time", None), naive=True) or now
        setattr(target, "create_time", create_time)
    if "update_time" in mapper_columns:
        update_time = shanghai_datetime(getattr(target, "update_time", None), naive=True) or now
        setattr(target, "update_time", update_time)
    if "create_timestamp" in mapper_columns and getattr(target, "create_timestamp", None) is None:
        setattr(target, "create_timestamp", now_ts)
    if "update_timestamp" in mapper_columns and getattr(target, "update_timestamp", None) is None:
        setattr(target, "update_timestamp", now_ts)


@event.listens_for(CustomBaseModel, "before_update", propagate=True)
def _before_update_set_audit_timezone(_mapper, _connection, target: CustomBaseModel) -> None:
    mapper_columns = target.__mapper__.columns
    if "update_time" in mapper_columns:
        update_time = shanghai_datetime(getattr(target, "update_time", None), naive=True) or shanghai_now(naive=True)
        setattr(target, "update_time", update_time)
    if "update_timestamp" in mapper_columns:
        setattr(target, "update_timestamp", int(time.time()))
EOF
)"

write_file "$APP_DIR/models/aps_task.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : aps_task.py

from sqlalchemy import JSON, String
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import CustomBaseModel


class ApsTask(CustomBaseModel):
    __table_name__ = "aps_tasks"

    task_id: Mapped[str] = mapped_column(String(64), nullable=False, comment="任务id")
    trigger_type: Mapped[str] = mapped_column(String(16), nullable=False, comment="触发器类型:date;interval;cron")
    trigger_param: Mapped[dict] = mapped_column(JSON, nullable=False, comment="触发器参数")
    task_function_name: Mapped[str | None] = mapped_column(String(255), nullable=True, comment="任务函数名称")
    task_function_args: Mapped[list] = mapped_column(JSON, nullable=False, default=list, comment="任务参数:args")
    task_function_kwargs: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict, comment="任务参数:kwargs")
EOF
)"

write_file "$APP_DIR/schemas/pagination.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : pagination.py

from pydantic import BaseModel, ConfigDict, Field


class CommonPage(BaseModel):
    model_config = ConfigDict(extra="ignore")

    page: int = Field(default=1, ge=1, description="页码")
    size: int = Field(default=20, ge=1, le=200, description="每页数量")


def page_size(page: int, size: int) -> tuple:
    return (page - 1) * size, size


def query_result(records: list, now_page: int, total: int) -> dict:
    res = {
        "records": records,
        "now_page": now_page,
        "total": total,
    }
    return res
EOF
)"

write_file "$APP_DIR/schemas/common.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : common.py

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class CommonPydanticCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="ignore",
    )

    remark: Optional[str] = Field(default=None, description="备注", examples=[""])
    creator: Optional[str] = Field(default=None, description="创建人(不需要传,从鉴权获取)")
    creator_id: Optional[int] = Field(default=None, description="创建人ID(不需要传,从鉴权获取)")

    def dict(self, **kwargs):
        return super().model_dump(exclude_unset=True, **kwargs)


class CommonPydanticUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        extra="ignore",
    )

    id: Optional[int] = Field(default=None, description="需要编辑的数据ID", examples=[1])
    remark: Optional[str] = Field(default=None, description="备注", examples=[""])
    modifier: Optional[str] = Field(default=None, description="更新人(不需要传,从鉴权获取)")
    modifier_id: Optional[int] = Field(default=None, description="更新人ID(不需要传,从鉴权获取)")

    def dict(self, **kwargs):
        return super().model_dump(exclude_unset=True, exclude_defaults=True, exclude_none=True, **kwargs)
EOF
)"

write_file "$APP_DIR/utils/time_tools.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : time_tools.py

from datetime import datetime

from dateutil import parser


class TimeTools:
    @staticmethod
    def timestamp_to_datetime(timestamp) -> str:
        dt_object = datetime.fromtimestamp(timestamp)
        str_date = dt_object.strftime("%Y-%m-%d %H:%M:%S")
        return str_date

    @staticmethod
    def datetime_to_timestamp(date_string, set_cn: bool = False, is_ms: bool = False):
        if not date_string:
            return 0

        datetime_object = datetime.strptime(date_string, "%Y-%m-%d %H:%M:%S")
        timestamp = datetime_object.timestamp()
        if set_cn:
            handle_timestamp = int(timestamp) + 28800
        else:
            handle_timestamp = int(timestamp)

        if is_ms:
            return handle_timestamp * 1000
        return handle_timestamp

    @staticmethod
    def today_zero_timestamp() -> int:
        today = datetime.now().date()
        midnight = datetime.combine(today, datetime.min.time())
        timestamp = int(midnight.timestamp())
        return timestamp

    @staticmethod
    def convert_to_standard_format(datetime_str) -> str:
        try:
            if isinstance(datetime_str, datetime):
                return datetime_str.strftime("%Y-%m-%d %H:%M:%S")
            dt = parser.parse(datetime_str)
            formatted_dt = dt.strftime("%Y-%m-%d %H:%M:%S")
            return formatted_dt
        except BaseException:
            return datetime_str
EOF
)"

write_file "$TARGET_DIR/tests/test_health.py" "$(cat <<EOF
from fastapi.testclient import TestClient

from app.main import app


client = TestClient(app)


def test_health_check() -> None:
    response = client.get("/api/v1/health")

    assert response.status_code == 200
    assert response.json() == {"status": "ok"}
EOF
)"

write_file "$TARGET_DIR/.env.example" "$(cat <<EOF
ENV="环境标识"

DOCS_TITLE="API文档标题"
DOCS_DESCRIPTION="API文档描述"
DOCS_SUMMARY="API文档总结"
DOCS_VERSION="API文档版本"
DOCS_OPENAPI_URL="API文档版本.json地址"

DB_BACKEND=mysql
SECRET_KEY=please-change-me
DEBUG=True
RUN_HOST=0.0.0.0
RUN_PORT=7777
SENSITIVE_HEADERS=authorization,cookie,set-cookie,x-api-key

MYSQL_HOSTNAME=127.0.0.1
MYSQL_USERNAME=root
MYSQL_PASSWORD=your-password
MYSQL_PORT=3306
MYSQL_DATABASE=database-name

POSTGRESQL_HOSTNAME=127.0.0.1
POSTGRESQL_USERNAME=postgres
POSTGRESQL_PASSWORD=your-password
POSTGRESQL_PORT=15432
POSTGRESQL_DATABASE=database-name

REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PWD=your-password
REDIS_DB=0
DECODE_RESPONSES=True

CELERY_BROKER_URL=
CELERY_RESULT_BACKEND=
CELERY_TASK_QUEUE="celery队列标识名称"
EOF
)"

write_file "$TARGET_DIR/.env.development" "$(cat <<EOF
ENV=development
SECRET_KEY=your-secret-key
DEBUG=True
RUN_HOST=0.0.0.0
RUN_PORT=7777
SENSITIVE_HEADERS=authorization,cookie,set-cookie,x-api-key

MYSQL_HOSTNAME=127.0.0.1
MYSQL_USERNAME=root
MYSQL_PASSWORD=12345678
MYSQL_PORT=3306
MYSQL_DATABASE=your-database-name

POSTGRESQL_HOSTNAME=127.0.0.1
POSTGRESQL_USERNAME=postgres
POSTGRESQL_PASSWORD=123456Abcd
POSTGRESQL_PORT=15432
POSTGRESQL_DATABASE=your-database-name

REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PWD=123456
REDIS_DB=0
DECODE_RESPONSES=True
EOF
)"

write_file "$TARGET_DIR/.env.test" "$(cat <<EOF
ENV=test
SECRET_KEY=your-secret-key
DEBUG=True
RUN_HOST=0.0.0.0
RUN_PORT=7778
SENSITIVE_HEADERS=authorization,cookie,set-cookie,x-api-key

MYSQL_HOSTNAME=127.0.0.1
MYSQL_USERNAME=root
MYSQL_PASSWORD=12345678
MYSQL_PORT=3306
MYSQL_DATABASE=your-database-name

POSTGRESQL_HOSTNAME=127.0.0.1
POSTGRESQL_USERNAME=postgres
POSTGRESQL_PASSWORD=123456Abcd
POSTGRESQL_PORT=15432
POSTGRESQL_DATABASE=your-database-name

REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PWD=123456
REDIS_DB=0
DECODE_RESPONSES=True
EOF
)"

write_file "$TARGET_DIR/.env.production" "$(cat <<EOF
ENV=production
SECRET_KEY=your-secret-key
DEBUG=False
RUN_HOST=0.0.0.0
RUN_PORT=5000
SENSITIVE_HEADERS=authorization,cookie,set-cookie,x-api-key

MYSQL_HOSTNAME=mariadb
MYSQL_USERNAME=root
MYSQL_PASSWORD=root12345678
MYSQL_PORT=3306
MYSQL_DATABASE=your-database-name

POSTGRESQL_HOSTNAME=127.0.0.1
POSTGRESQL_USERNAME=postgres
POSTGRESQL_PASSWORD=123456Abcd
POSTGRESQL_PORT=15432
POSTGRESQL_DATABASE=your-database-name

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PWD=123456
REDIS_DB=0
DECODE_RESPONSES=True
EOF
)"

write_file "$TARGET_DIR/.env.staging" "$(cat <<EOF
ENV=staging
SECRET_KEY=your-secret-key
DEBUG=False
RUN_HOST=0.0.0.0
RUN_PORT=5001
SENSITIVE_HEADERS=authorization,cookie,set-cookie,x-api-key

MYSQL_HOSTNAME=mariadb
MYSQL_USERNAME=root
MYSQL_PASSWORD=root12345678
MYSQL_PORT=3306
MYSQL_DATABASE=your-database-name

POSTGRESQL_HOSTNAME=127.0.0.1
POSTGRESQL_USERNAME=postgres
POSTGRESQL_PASSWORD=123456Abcd
POSTGRESQL_PORT=15432
POSTGRESQL_DATABASE=your-database-name

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PWD=123456
REDIS_DB=0
DECODE_RESPONSES=True
EOF
)"

write_file "$TARGET_DIR/scripts/dev.sh" "$(cat <<EOF
#!/usr/bin/env bash

set -euo pipefail

uvicorn app.main:app --reload
EOF
)"

write_file "$TARGET_DIR/pyproject.toml" "$(cat <<EOF
[project]
name = "${PROJECT_NAME}"
version = "0.1.0"
description = "Project scaffold generated by ${SCRIPT_NAME}"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "apscheduler>=3.10.4",
  "httpx>=0.27.2",
  "bcrypt>=4.2.0",
  "celery>=5.4.0",
  "fastapi>=0.115.0",
  "loguru>=0.7.2",
  "pydantic-settings>=2.5.2",
  "python-dateutil>=2.9.0.post0",
  "pytz>=2024.1",
  "redis>=5.0.8",
  "shortuuid>=1.0.13",
  "sqlalchemy>=2.0.36",
  "asyncmy>=0.2.9",
  "asyncpg>=0.30.0",
  "uvicorn[standard]>=0.30.6",
  "email-validator>=2.3.0",
]

[dependency-groups]
dev = [
  "alembic>=1.14.1",
  "pytest>=8.3.2",
]

[tool.uv]
package = false

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"
EOF
)"

write_file "$TARGET_DIR/README.md" "$(cat <<EOF
# ${PROJECT_NAME}

Author: ${AUTHOR}
EOF
)"

write_file "$TARGET_DIR/local_run.py" "$(cat <<EOF
# -*- coding: utf-8 -*-
# @Time    : ${CURRENT_TIME}
# @Author  : ${AUTHOR}
# @File    : local_run.py

import uvicorn


if __name__ == "__main__":
    uvicorn.run("app.main:app", host="0.0.0.0", port=7769, reload=True)
EOF
)"

if [[ "$DRY_RUN" -ne 1 ]]; then
  chmod +x "$TARGET_DIR/scripts/dev.sh"
fi

log "project initialization complete"
